status = [
  "continuous-integration/travis-ci/push",
  "test (1.%, ubuntu-latest, x86)",
  "test (1, ubuntu-latest, x86)",
  "test (1.%, ubuntu-latest, x64)",
  "test (1, ubuntu-latest, x64)",
  "test (1.%, macOS-latest, x64)",
  "test (1, macOS-latest, x64)",
  "test (1.%, windows-latest, x86)",
  "test (1, windows-latest, x86)",
  "test (1.%, windows-latest, x64)",
  "test (1, windows-latest, x64)"
]
delete_merged_branches = true
# Uncomment this to require at least on approval of a project member.
#required_approvals = 1
# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200